//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DM Helper.rc
//
#define ID_ADD                          3
#define IDDELETE                        3
#define IDC_SPELL_INFO                  3
#define IDC_MAP_SFX                     3
#define IDOK2                           3
#define IDC_ROLL_BUTTON                 3
#define IDCANCEL2                       3
#define IDC_CLEAR_SFX                   4
#define IDC_ADD_ROLL_BUTTON             4
#define IDREPOSITION                    4
#define IDC_CLEAR_BUTTON                5
#define IDPREVIEW                       5
#define IDC_PLAY_SFX                    5
#define ID_UP                           6
#define ID_DOWN                         7
#define ID_LEFT                         8
#define ID_RIGHT                        9
#define ID_SCALE_UP                     10
#define ID_SCALE_DOWN                   11
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_DMHELPER_DIALOG             102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDD_CHAR_VIEW_DIALOG            129
#define IDD_CHAR_SHEET_DIALOG           130
#define IDB_FIGHTER_BITMAP              131
#define IDB_SAVE_ICON_BITMAP            133
#define IDI_MAIN_ICON                   134
#define IDD_MAP_VIEW_DIALOG             135
#define IDB_COVER_BITMAP                136
#define IDB_KEOLAND_BITMAP              137
#define IDB_FURYONDY_BITMAP             138
#define IDD_SOUND_FX_DIALOG             139
#define IDW_SQUEAK_DOOR                 140
#define IDW_SMASHING_DOOR               142
#define IDW_GLASS_BREAK                 143
#define IDW_GHOST                       144
#define IDW_ARROW_THUMP                 145
#define IDW_SWORD_UNSHEATHE             146
#define IDW_SWORD_FIGHT                 147
#define IDW_MALE_SCREAM                 149
#define IDW_FEMALE_SCREAM               150
#define IDW_FIREBALL                    151
#define IDW_LIGHTNING                   152
#define IDW_MAGIC_WAND                  153
#define IDW_CHANT                       154
#define IDW_CHOIR                       155
#define IDB_CLERIC_BITMAP               156
#define IDB_MAGICUSER_BITMAP            157
#define IDB_THIEF_BITMAP                158
#define IDB_MULTICLASS_BITMAP           160
#define IDD_HP_EDIT_DIALOG              161
#define IDD_MAP_EDIT_DIALOG             162
#define IDB_CAMERA_ICON_BITMAP          164
#define IDB_RIGHT_ICON_BITMAP           165
#define IDB_LEFT_ICON_BITMAP            166
#define IDB_SWAP_ICON_BITMAP            167
#define IDB_PRINT_ICON_BITMAP           168
#define IDD_MOD_VALUE_DIALOG            169
#define IDR_MAIN_MENU                   170
#define IDD_INVENTORY_DIALOG            172
#define IDB_INVENTORY_BITMAP            174
#define IDD_LOAD_FILE_DIALOG            175
#define IDB_PH_BITMAP                   176
#define IDD_PARTY_DIALOG                177
#define IDB_SPELLBOOK_BITMAP            178
#define IDD_CHARACTER_SELECTOR_DIALOG   179
#define IDB_EXPAND_DOWN_BITMAP          181
#define IDB_EXPAND_UP_BITMAP            183
#define IDD_CHAR_SPELLS_DIALOG          184
#define IDD_SPELL_DESC_DIALOG           187
#define IDD_TIME_EDIT_DIALOG            190
#define IDB_UP_ARROW_BITMAP             191
#define IDB_DOWN_ARROW_BITMAP           193
#define IDB_UP_ARROW_PRESSED_BITMAP     194
#define IDB_DOWN_ARROW_PRESSED_BITMAP   195
#define IDD_SPELL_CAST_DIALOG           196
#define IDD_SOUNDBOARD_DIALOG           197
#define IDD_SFX_EDITOR_DIALOG           198
#define IDR_CLOISTER_BLACK_FONT         205
#define IDD_SFX_MAPPER_DIALOG           206
#define IDD_NPC_VIEW_DIALOG             208
#define IDB_LARGE_RIGHT_BITMAP          210
#define _                               211
#define IDB_LARGE_LEFT_BITMAP           211
#define IDD_ABOUT_DIALOG                212
#define IDD_DICE_ROLLER_DIALOG          213
#define IDB_D20_BITMAP                  214
#define IDB_D12_BITMAP                  215
#define IDB_D10_BITMAP                  216
#define IDB_D8_BITMAP                   217
#define IDB_D6_BITMAP                   218
#define IDB_D4_BITMAP                   219
#define IDB_D100_BITMAP                 220
#define IDB_BITMAP1                     221
#define IDB_DX_BITMAP                   221
#define IDD_PC_DETAILS_DIALOG           222
#define IDD_DIALOG1                     223
#define IDD_CALENDAR_DIALOG             223
#define IDB_CALENDAR_CELL_BITMAP        224
#define IDB_LARGE_LEFT_BLACK_BITMAP     225
#define IDB_LARGE_RIGHT_BLACK_BITMAP    226
#define IDD_SAVE_CONFIRM_DIALOG         227
#define IDB_PARCHMENT_BITMAP            228
#define IDD_DIALOG2                     229
#define IDD_PARTY_LOG_DIALOG            229
#define IDD_EVENT_LOGGER_DIALOG         230
#define IDD_INPUT_DIALOG                231
#define IDD_INITIATIVE_DIALOG           232
#define IDB_MOON_CELLS_BITMAP           233
#define IDD_MUNDANE_TYPE_SELECTOR_DIALOG 234
#define IDD_SCROLL_DETAILS_DIALOG       235
#define IDD_SPELL_SELECTOR_DIALOG       236
#define IDD_CONTAINER_DETAILS_DIALOG    237
#define IDB_SCROLL_BITMAP               239
#define IDD_RANDOM_ENCOUNTER_DIALOG     240
#define IDD_LANGUAGE_SELECT_DIALOG      241
#define IDD_DUNGEON_MONSTER_DIALOG      242
#define IDD_SUBPARTY_DIALOG             243
#define IDD_DIALOG3                     244
#define IDD_BASE_NPC_DIALOG             244
#define IDD_CHAR_NOTES_DIALOG           245
#define IDD_TREASURE_TYPE_DIALOG        246
#define IDD_MAGIC_SWORD_PROPERTIES_DIALOG 247
#define IDD_STRING_SELECTOR_DIALOG      248
#define IDD_CUSTOM_ITEM_DIALOG          249
#define IDD_CUSTOM_SPELL_DIALOG         250
#define IDD_CUSTOM_MONSTER_DIALOG       251
#define IDD_CUSTOM_ARMOR_DIALOG         252
#define IDD_CUSTOM_WEAPON_DIALOG        253
#define IDD_TEST_DIALOG                 254
#define IDD_ITEM_DESCRIPTION_DIALOG     255
#define IDD_DM_FILE_MANAGER_DIALOG      256
#define IDB_FOLDER_ICON_BITMAP          258
#define IDB_UP_FOLDER_BITMAP            259
#define IDB_UP_FOLDER_ICON_BITMAP       259
#define IDB_MINI_PORTRAIT_BACKDROP_BITMAP 260
#define IDB_NPC_PORTRAIT_BACKDROP_BITMAP 261
#define IDD_PORTRAIT_SELECT_DIALOG      262
#define IDD_MAP_LAYER_EDIT_DIALOG       263
#define IDD_DETACHED_MAP_DIALOG         264
#define IDD_MAP_SIZING_DIALOG           265
#define IDD_NAME_MAP_DIALOG             267
#define IDB_FOG_OF_WAR_BITMAP           268
#define IDD_MAP_SFX_DIALOG              269
#define IDB_SFX_BUTTON_BITMAP           270
#define IDB_LIGHTING_ALPHA_BITMAP       271
#define IDB_RAIN_BITMAP                 272
#define IDB_SNOW_BITMAP                 273
#define IDD_WEATHER_DIALOG              275
#define IDB_BITMAP2                     276
#define IDB_RAIN_SPLAT_BITMAP           276
#define IDD_PDF_VIEW_DIALOG             278
#define IDB_WIDE_LEFT_BUTTON_BITMAP     280
#define IDB_WIDE_RIGHT_BUTTON_BITMAP    281
#define IDB_ZOOM_IN_BUTTON_BITMAP       282
#define IDB_ZOOM_OUT_BUTTON_BITMAP      283
#define IDD_DIALOG4                     284
#define IDD_CHARACTER_PORTRAIT_DIALOG   284
#define IDD_CUSTOM_CLASS_DIALOG         286
#define IDB_SWORD_ICON_BITMAP           287
#define IDD_ADD_ON_DIALOG               288
#define IDB_CENTER_BUTTON_BITMAP        290
#define IDD_PICK_LOCK_DIALOG            291
#define IDD_RANDOM_NAME_GENERATOR_DIALOG 292
#define IDD_STRIKEORTHROW_DIALOG        293
#define IDD_SPELL_COMPONENTS_DIALOG     294
#define IDD_DM_REMINDER_SFX_DIALOG      295
#define IDD_SAVING_THROW_MOD_DIALOG     296
#define IDD_THIEF_SKILL_MODIFIER_DIALOG 297
#define IDD_DIALOG5                     298
#define IDD_ASSASSIN_SKILL_MODIFIER_DIALOG 298
#define IDD_CLERIC_SKILL_MODIFIER_DIALOG 299
#define IDD_CHART_LOOKUP_DIALOG         300
#define IDC_CHAR_VIEW                   1000
#define IDC_CHAR_NAME_EDIT              1001
#define IDC_PARTY_VIEW                  1001
#define IDC_CHAR_RACE_COMBO             1002
#define IDC_MAP_VIEW                    1002
#define IDC_CHAR_CLASS_COMBO_1          1003
#define IDC_SOUND_FX                    1003
#define IDC_CHAR_CLASS_COMBO_2          1004
#define IDC_CHAR_CLASS_COMBO_3          1005
#define IDC_MULTICLASS_STATIC           1006
#define IDC_MULTICLASS_STATIC2          1007
#define IDC_STR_EDIT                    1008
#define IDC_EX_STR_EDIT                 1009
#define IDC_ROLL_STATS                  1010
#define IDC_INT_EDIT                    1011
#define IDC_UA_CHECK                    1011
#define IDC_WIS_EDIT                    1012
#define IDC_LEVEL_LIMITS_CHECK          1012
#define IDC_EGO_EDIT                    1012
#define IDC_DEX_EDIT                    1013
#define IDC_HIT_POINTS_REROLL_CHECK     1013
#define IDC_PRIMARY_ABILITY_EDIT_1      1013
#define IDC_CON_EDIT                    1014
#define IDC_HIT_POINTS_REROLL_HALF_CHECK 1014
#define IDC_PRIMARY_ABILITY_EDIT_2      1014
#define IDC_CHA_EDIT                    1015
#define IDC_HIT_POINTS_MAX_FIRST_LEVEL_CHECK 1015
#define IDC_PRIMARY_ABILITY_EDIT_3      1015
#define IDC_COM_EDIT                    1016
#define IDC_D10_INITIATIVE_CHECK        1016
#define IDC_EXCEPTIONAL_POWER_EDIT      1016
#define IDC_CHAR_SEX_COMBO              1017
#define IDC_SOUND_EFFECTS_CHECK         1017
#define IDC_SPECIAL_PURPOSE_EDIT        1017
#define IDC_LEVEL_EDIT_1                1018
#define IDC_RANDOM_NAME_CHECK           1018
#define IDC_SPECIAL_PURPOSE_POWER_EDIT  1018
#define IDC_XP_EDIT_1                   1019
#define IDC_MONKS_STRENGTH_CHECK        1019
#define IDC_LANGUAGES_EDIT              1019
#define IDC_LEVEL_EDIT_2                1020
#define IDC_MONKS_DEXDERITY_CHECK       1020
#define IDC_XP_EDIT_2                   1021
#define IDC_AUTO_UPDATE_CHECK           1021
#define IDC_LEVEL_EDIT_3                1022
#define IDC_MONSTER_MANUAL_II_CHECK     1022
#define IDC_XP_EDIT_3                   1023
#define IDC_FIEND_FOLIO_CHECK           1023
#define IDC_HP_EDIT                     1024
#define IDC_USE_WEAPONS_VS_AC_CHECK     1024
#define IDC_HP_CURRENT_EDIT             1025
#define IDC_SMALL_FONT_CHECK            1025
#define IDC_CHAR_SHEET                  1026
#define IDC_SPELL_COMPONENTS_CHECK      1026
#define IDC_HP_BY_LEVEL                 1027
#define IDC_SHOW_HP_CHECK               1028
#define IDC_CON_COMMENT                 1029
#define IDC_DEX_COMMENT                 1030
#define IDC_STR_COMMENT                 1031
#define IDC_CHAR_ALIGNMENT_COMBO        1032
#define IDC_CHAR_ARMOR_COMBO            1033
#define IDC_CHAR_SHIELD_COMBO           1034
#define IDC_WEAPON_CHART_LIST           1035
#define IDC_ARMOR_PLUS_EDIT             1036
#define IDC_SHIELD_PLUS_EDIT            1037
#define IDC_AC_EDIT                     1038
#define IDC_SAVE_BUTTON                 1039
#define IDC_WEAPON_COMBO_1              1039
#define IDC_BACKGROUND_BITMAP           1040
#define IDC_WEAPON_PLUS_EDIT_1          1040
#define IDC_PORTRAIT_BUTTON             1040
#define IDC_SOUND_BUTTON1               1041
#define IDC_WEAPON_COMBO_2              1041
#define IDC_FLIP_PAGE_BUTTON            1041
#define IDC_SOUND_BUTTON2               1042
#define IDC_WEAPON_PLUS_EDIT_2          1042
#define IDC_PRINT_BUTTON                1042
#define IDC_SOUND_BUTTON3               1043
#define IDC_WEAPON_COMBO_3              1043
#define IDC_PAGE_BACK_BUTTON            1043
#define IDC_SOUND_BUTTON4               1044
#define IDC_WEAPON_PLUS_EDIT_3          1044
#define IDC_HP_EDIT_1_1                 1044
#define IDC_PAGE_FWD_BUTTON             1044
#define IDC_SOUND_BUTTON5               1045
#define IDC_WEAPON_COMBO_4              1045
#define IDC_HP_EDIT_1_2                 1045
#define IDC_ZOOM_IN_BUTTON              1045
#define IDC_SOUND_BUTTON6               1046
#define IDC_WEAPON_PLUS_EDIT_4          1046
#define IDC_HP_EDIT_1_3                 1046
#define IDC_ZOOM_OUT_BUTTON             1046
#define IDC_SOUND_BUTTON7               1047
#define IDC_LOAD                        1047
#define IDC_HP_EDIT_1_4                 1047
#define IDC_NPC_PORTRAIT_BUTTON         1047
#define IDC_SEARCH_BUTTON               1047
#define IDC_SOUND_BUTTON8               1048
#define IDC_SAVE                        1048
#define IDC_HP_EDIT_1_5                 1048
#define IDC_SOUND_BUTTON9               1049
#define IDC_INT_COMMENT                 1049
#define IDC_HP_EDIT_1_6                 1049
#define IDC_SOUND_BUTTON10              1050
#define IDC_HP_EDIT_1_7                 1050
#define IDC_SAVE_EDIT_1                 1050
#define IDC_SOUND_BUTTON11              1051
#define IDC_HP_EDIT_1_8                 1051
#define IDC_SAVE_EDIT_2                 1051
#define IDC_SOUND_BUTTON12              1052
#define IDC_HP_EDIT_1_9                 1052
#define IDC_SAVE_EDIT_3                 1052
#define IDC_SOUND_BUTTON13              1053
#define IDC_HP_EDIT_1_10                1053
#define IDC_WIS_COMMENT                 1053
#define IDC_ATTACK_COMMENT              1053
#define IDC_SOUND_BUTTON14              1054
#define IDC_HP_EDIT_1_11                1054
#define IDC_SAVE_EDIT_4                 1054
#define IDC_ATTACK_COMMENT2             1054
#define IDC_HP_EDIT_1_12                1055
#define IDC_SAVE_EDIT_5                 1055
#define IDC_HP_EDIT_1_13                1056
#define IDC_CHA_COMMENT                 1056
#define IDC_DEFENSE_COMMENT             1056
#define IDC_HP_EDIT_1_14                1057
#define IDC_THIEF_SKILL_EDIT_1          1057
#define IDC_INT_COMMENT2                1057
#define IDC_MR_COMMENT                  1057
#define IDC_HP_EDIT_1_15                1058
#define IDC_THIEF_SKILL_EDIT_2          1058
#define IDC_DESC_COMMENT                1058
#define IDC_HP_EDIT_1_16                1059
#define IDC_THIEF_SKILL_EDIT_3          1059
#define IDC_SIZE_COMMENT                1059
#define IDC_HP_EDIT_1_17                1060
#define IDC_THIEF_SKILL_EDIT_4          1060
#define IDC_TT_COMMENT                  1060
#define IDC_HP_EDIT_1_18                1061
#define IDC_THIEF_SKILL_EDIT_5          1061
#define IDC_HP_EDIT_1_19                1062
#define IDC_THIEF_SKILL_EDIT_6          1062
#define IDC_CLASS_1_STATIC              1063
#define IDC_THIEF_SKILL_EDIT_7          1063
#define IDC_THIEF_SKILL_EDIT_8          1064
#define IDC_SWAP_BUTTON_1               1065
#define IDC_LL_STATIC_1                 1066
#define IDC_SWAP_BUTTON_2               1066
#define IDC_EDIT_BUTTON                 1067
#define IDC_SWAP_BUTTON_3               1067
#define IDC_MAP_NAME_EDIT               1068
#define IDC_LOAD_BUTTON                 1068
#define IDC_SPELL_CHART_LIST            1068
#define IDC_CHAR_RING_R_COMBO           1068
#define IDC_DELETE_BUTTON               1068
#define IDC_MAP_ROWS_EDIT               1069
#define IDC_ADD_XP_BUTTON_1             1069
#define IDC_PARTY_XP_EDIT               1069
#define IDC_INSERT_BUTTON               1069
#define IDC_DETACH_BUTTON               1069
#define IDC_MAP_COLUMNS_EDIT            1070
#define IDC_ADD_XP_BUTTON_2             1070
#define IDC_ADD_EDIT                    1070
#define IDC_ERASE_BUTTON                1070
#define IDC_FLIP_BUTTON                 1070
#define IDC_MAP_PIXELS_X_EDIT           1071
#define IDC_ADD_XP_BUTTON_3             1071
#define IDC_MAIN_TAB                    1071
#define IDC_CENTER_BUTTON               1071
#define IDC_MAP_PIXELS_Y_EDIT           1072
#define IDC_CHAR_INVENTORY              1072
#define IDC_25MM_BUTTON                 1072
#define IDC_AMMO_COMBO                  1073
#define IDC_MAP_SCALE_EDIT              1073
#define IDC_CW_STATIC                   1074
#define IDC_AMMO_PLUS_EDIT              1074
#define IDC_MAP_WEATHER_BASE_COORD_EDIT 1074
#define IDC_OPT_STATIC                  1075
#define IDC_ADD_HP_BUTTON               1075
#define IDC_MAP_LATITUDE_MILES_EDIT     1075
#define IDC_CHAR_NAME_STATIC            1076
#define IDC_ROOM_OCC_EDIT               1076
#define IDC_OPT_STATIC2                 1076
#define IDC_ANCHOR_BUTTON1              1077
#define IDC_CHAR_NAME_STATIC2           1077
#define IDC_TRANS_COLOR_RED             1077
#define IDC_SPELLS_TOP_TAB              1078
#define IDC_CHAR_NAME_STATIC3           1078
#define IDC_RECOVER_AMMO_COMBO          1078
#define IDC_TRANS_COLOR_GREEN           1078
#define IDC_SPELLS_LEVEL_TAB            1079
#define IDC_FREEB_BUTTON                1079
#define IDC_RING_R_PLUS_EDIT            1079
#define IDC_DEBUG_BUTTON                1079
#define IDC_AMMO_FIRED_EDIT             1080
#define IDC_CHAR_RING_L_COMBO           1080
#define IDC_DEBUG_BUTTON2               1080
#define IDC_TRANS_COLOR_BLUE            1080
#define IDC_STORE_LIST                  1081
#define IDC_RECOVER_AMMO                1081
#define IDC_DEBUG_BUTTON3               1081
#define IDC_TILE_HEIGHT_EDIT            1081
#define IDC_HP_EDIT_2_1                 1082
#define IDC_INVENTORY_LIST              1082
#define IDC_NUM_ATTACKS_EDIT            1082
#define IDC_DEBUG_BUTTON4               1082
#define IDC_HP_EDIT_2_2                 1083
#define IDC_BUY_BUTTON                  1083
#define IDC_SPELLS_MODE_TAB             1083
#define IDC_RING_L_PLUS_EDIT            1083
#define IDC_CONTAINER_LIST              1083
#define IDC_HP_EDIT_2_3                 1084
#define IDC_GIVE_BUTTON                 1084
#define IDC_MEMORIZE_SPELL              1084
#define IDC_ASS_SKILL_EDIT_1            1084
#define IDC_HP_EDIT_2_4                 1085
#define IDC_GIVE_TO_COMBO               1085
#define IDC_FORGET_SPELL                1085
#define IDC_ASS_SKILL_EDIT_2            1085
#define IDC_HP_EDIT_2_5                 1086
#define IDC_FIRE_AMMO_BUTTON            1086
#define IDC_GIVE_TO_BUTTON              1086
#define IDC_HP_EDIT_2_6                 1087
#define IDC_DROP_BUTTON                 1087
#define IDC_STORE_SPELLS                1087
#define IDC_ASS_SKILL_EDIT_3            1087
#define IDC_HP_EDIT_2_7                 1088
#define IDC_PP_EDIT                     1088
#define IDC_RESTORE_SPELLS              1088
#define IDC_ASS_SKILL_EDIT_4            1088
#define IDC_HP_EDIT_2_8                 1089
#define IDC_GP_EDIT                     1089
#define IDC_ASS_SKILL_EDIT_5            1089
#define IDC_HP_EDIT_2_9                 1090
#define IDC_EP_EDIT                     1090
#define IDC_ASS_SKILL_EDIT_6            1090
#define IDC_HP_EDIT_2_10                1091
#define IDC_SP_EDIT                     1091
#define IDC_ASS_SKILL_EDIT_7            1091
#define IDC_HP_EDIT_2_11                1092
#define IDC_CP_EDIT                     1092
#define IDC_ASS_SKILL_EDIT_8            1092
#define IDC_HP_EDIT_2_12                1093
#define IDC_RADIO_1                     1093
#define IDC_ASS_SKILL_EDIT_9            1093
#define IDC_HP_EDIT_2_13                1094
#define IDC_RADIO_2                     1094
#define IDC_ASS_SKILL_EDIT_10           1094
#define IDC_HP_EDIT_2_14                1095
#define IDC_RADIO_3                     1095
#define IDC_MOVE_EDIT                   1095
#define IDC_HP_EDIT_2_15                1096
#define IDC_RADIO_4                     1096
#define IDC_SPECIAL_ATTACK_COMMENT      1096
#define IDC_HP_EDIT_2_16                1097
#define IDC_RADIO_5                     1097
#define IDC_SPECIAL_DEFENSE_COMMENT     1097
#define IDC_HP_EDIT_2_17                1098
#define IDC_ADD_SUB_BUTTON              1098
#define IDC_CHAR_HELM_COMBO             1098
#define IDC_HP_EDIT_2_18                1099
#define IDC_STACK_COIN_BUTTON           1099
#define IDC_TURN_UNDEAD_EDIT_1          1099
#define IDC_HP_EDIT_2_19                1100
#define IDC_STACK_INV_BUTTON            1100
#define IDC_TURN_UNDEAD_EDIT_2          1100
#define IDC_ENC_EDIT                    1101
#define IDC_EXP_EDIT                    1101
#define IDC_HP_EDIT_3_1                 1102
#define IDC_MAX_ENC_STATIC              1102
#define IDC_ADD_EXP_BUTTON              1102
#define IDC_HP_EDIT_3_2                 1103
#define IDC_PRICES_CHECK                1103
#define IDC_EXP_VALUE_EDIT              1103
#define IDC_HP_EDIT_3_3                 1104
#define IDC_DROP_ALL_BUTTON             1104
#define IDC_TURN_UNDEAD_EDIT_3          1104
#define IDC_HP_EDIT_3_4                 1105
#define ID_OK                           1105
#define IDC_TURN_UNDEAD_EDIT_4          1105
#define IDC_HP_EDIT_3_5                 1106
#define IDC_WEAPONS_CHECK               1106
#define IDC_FILE_LIST                   1106
#define IDC_TURN_UNDEAD_EDIT_5          1106
#define IDC_HP_EDIT_3_6                 1107
#define IDC_ARMOR_CHECK                 1107
#define IDC_FILENAME_EDIT               1107
#define IDC_TURN_UNDEAD_EDIT_6          1107
#define IDC_HP_EDIT_3_7                 1108
#define IDC_SHIELDS_CHECK               1108
#define IDC_PARTY_LIST                  1108
#define IDC_TURN_UNDEAD_EDIT_7          1108
#define IDC_HP_EDIT_3_8                 1109
#define IDC_EQUIP_CHECK                 1109
#define IDC_PARTY_LIST2                 1109
#define IDC_TURN_UNDEAD_EDIT_8          1109
#define IDC_HP_EDIT_3_9                 1110
#define IDC_MISC_WEAPONS_CHECK          1110
#define IDC_PARTY_NAME_EDIT             1110
#define IDC_TURN_UNDEAD_EDIT_9          1110
#define IDC_HP_EDIT_3_10                1111
#define IDC_TOTAL_STATIC                1111
#define IDC_TURN_UNDEAD_EDIT_10         1111
#define IDC_HP_EDIT_3_11                1112
#define IDC_ADD_CUSTOM_BUTTON           1112
#define IDC_TURN_UNDEAD_EDIT_11         1112
#define IDC_HP_EDIT_3_12                1113
#define IDC_PROFF_LIST                  1113
#define IDC_TURN_UNDEAD_EDIT_12         1113
#define IDC_HP_EDIT_3_13                1114
#define IDC_WEP_PROF_STATIC             1114
#define IDC_TURN_UNDEAD_EDIT_13         1114
#define IDC_HP_EDIT_3_14                1115
#define IDC_ADD_PROFF                   1115
#define IDC_SPELLS_STATIC               1115
#define IDC_CHAR_VISION_COMBO           1115
#define IDC_HP_EDIT_3_15                1116
#define IDC_REMOVE_PROFF                1116
#define IDC_THIEF_STATIC_1              1116
#define IDC_HP_EDIT_3_16                1117
#define IDC_NON_WEP_PROF_STATIC         1117
#define IDC_THIEF_STATIC_2              1117
#define IDC_HP_EDIT_3_17                1118
#define IDC_THIEF_STATIC_3              1118
#define IDC_RINGS_CHECK                 1118
#define IDC_HP_EDIT_3_18                1119
#define IDC_THIEF_STATIC_4              1119
#define IDC_WEIGHTS_CHECK               1119
#define IDC_HP_EDIT_3_19                1120
#define IDC_THIEF_STATIC_5              1120
#define IDC_ADD_SUB_BUTTON2             1120
#define IDC_MAGIC_ADJ_BUTTON            1120
#define IDC_CLASS_2_STATIC              1121
#define IDC_THIEF_STATIC_6              1121
#define IDC_ITEM_XP_EDIT                1121
#define IDC_CLASS_3_STATIC              1122
#define IDC_THIEF_STATIC_7              1122
#define IDC_GIVE_WITH_XP_CHARACTER_CHECK 1122
#define IDC_LL_STATIC_2                 1123
#define IDC_THIEF_STATIC_8              1123
#define IDC_GIVE_WITH_XP_PARTY_CHECK    1123
#define IDC_LL_STATIC_3                 1124
#define IDC_THIEF_STATIC_0              1124
#define IDC_DROP_WITH_XP_CHARACTER_CHECK 1124
#define IDC_LL_STATIC_4                 1125
#define IDC_ASS_STATIC_1                1125
#define IDC_DROP_WITH_XP_PARTY_CHECK    1125
#define IDC_LL_STATIC_5                 1126
#define IDC_MAP_LEGEND                  1126
#define IDC_ASS_STATIC_2                1126
#define IDC_POTIONS_CHECK               1126
#define IDC_LL_STATIC_6                 1127
#define IDC_ASS_STATIC_3                1127
#define IDC_MAGICAL_ARMOR_CHECK         1127
#define IDC_LL_STATIC_7                 1128
#define IDC_ASS_STATIC_4                1128
#define IDC_MAGICAL_ARMOR_CHECK2        1128
#define IDC_MAGICAL_SWORDS_CHECK        1128
#define IDC_LL_STATIC_8                 1129
#define IDC_BUTTON1                     1129
#define IDC_ASS_STATIC_5                1129
#define IDC_RODS_STAVES_WANDS_CHECK     1129
#define IDC_LL_STATIC_9                 1130
#define IDC_BUTTON2                     1130
#define IDC_SPELLS_REMAINING            1130
#define IDC_ASS_STATIC_6                1130
#define IDC_MISC_MAGIC_1_CHECK          1130
#define IDC_LL_STATIC_10                1131
#define IDC_BUTTON3                     1131
#define IDC_CHARACTER_LIST              1131
#define IDC_SPELLS_REMAINING_SPELLBOOK  1131
#define IDC_ASS_STATIC_7                1131
#define IDC_MISC_MAGIC_2_CHECK          1131
#define IDC_LL_STATIC_11                1132
#define IDC_BUTTON4                     1132
#define IDC_ADD_MEMBER_BUTTON           1132
#define IDC_ASS_STATIC_8                1132
#define IDC_MISC_MAGIC_3_CHECK          1132
#define IDC_LL_STATIC_12                1133
#define IDC_BUTTON5                     1133
#define IDC_DELETE_MEMBER_BUTTON        1133
#define IDC_EXPAND_SPELL_LIST_BUTTON    1133
#define IDC_ASS_STATIC_0                1133
#define IDC_MISC_MAGIC_4_CHECK          1133
#define IDC_LL_STATIC_13                1134
#define IDC_BUTTON6                     1134
#define IDC_ADD_LOAD_PARTY_BUTTON       1134
#define IDC_CONTRACT_SPELL_LIST_BUTTON  1134
#define IDC_ASS_STATIC_9                1134
#define IDC_MISC_MAGIC_5_CHECK          1134
#define IDC_LL_STATIC_14                1135
#define IDC_BUTTON7                     1135
#define IDC_DELETE_SAVE_PARTY_BUTTON    1135
#define IDC_HIDER                       1135
#define IDC_ASS_STATIC_10               1135
#define IDC_MISC_MAGIC_SPECIAL_CHECK    1135
#define IDC_LL_STATIC_15                1136
#define IDC_BUTTON8                     1136
#define IDC_SPELLS_BUTTON               1136
#define IDC_ATTACK_HIT_BUTTON           1136
#define IDC_XP_CHECK                    1136
#define IDC_LL_STATIC_16                1137
#define IDC_BUTTON9                     1137
#define IDC_SPELL_BOOK_LIST             1137
#define IDC_ATTACK_MISS_BUTTON          1137
#define IDC_SCROLLS_CHECK               1137
#define IDC_TURN_STATIC_1               1137
#define IDC_LL_STATIC_17                1138
#define IDC_BUTTON10                    1138
#define IDC_SPELLS_MEMORIZED_LIST       1138
#define IDC_CAST_SPELL_BUTTON           1138
#define IDC_TURN_STATIC_2               1138
#define IDC_TREASURE_TYPE_BUTTON        1138
#define IDC_LL_STATIC_18                1139
#define IDC_BUTTON_BACK                 1139
#define IDC_SPELLBOOK_STATIC            1139
#define IDC_MISSILE_HIT_BUTTON          1139
#define IDC_SECONDARY_SKILL_COMMENT     1139
#define IDC_ITEM_INFO_BUTTON            1139
#define IDC_PING_BUTTON                 1140
#define IDC_WOUND_BUTTON                1140
#define IDC_BUTTON_ALL                  1140
#define IDC_CONCEALED_MOVE_EDIT         1140
#define IDC_GEN_TREASURE_BUTTON         1140
#define IDC_SPELL_DESC_EDIT             1141
#define IDC_HEAL_BUTTON                 1141
#define IDC_CLIMBING_MOVE_EDIT          1141
#define IDC_MAGIC_COMPONENTS_CHECK      1141
#define IDC_MISSILE_MISS_BUTTON         1142
#define IDC_SPECIAL_MOVE_EDIT           1142
#define IDC_ITEM_DESC                   1142
#define IDC_DESC_1                      1143
#define IDC_COPY_MEMBER_BUTTON          1143
#define IDC_TOOL_TIP                    1143
#define IDC_DESC_2                      1144
#define IDC_CREATE_NPC_BUTTON           1144
#define IDC_DESC_3                      1145
#define IDC_DELETE_NPC_BUTTON           1145
#define IDC_DESC_4                      1146
#define IDC_PASTE_MEMBER_BUTTON         1146
#define IDC_DESC_5                      1147
#define IDC_ATTACK_HIT_BUTTON2          1147
#define IDC_DESC_6                      1148
#define IDC_ATTACK_MISS_BUTTON2         1148
#define IDC_FAKE_EDIT                   1149
#define IDC_CAST_SPELL_BUTTON2          1149
#define IDC_ANCHOR_BUTTON               1150
#define IDC_WOUND_BUTTON2               1151
#define IDC_MILES_RADIO                 1152
#define IDC_HEAL_BUTTON2                1152
#define IDC_FEET_RADIO                  1153
#define IDC_PARTY_COMBO                 1153
#define IDC_MISSILE_HIT_BUTTON2         1153
#define IDC_CHARACTER_COMBO             1154
#define IDC_MISSILE_MISS_BUTTON2        1154
#define IDC_BDROP                       1155
#define IDC_PARTY_COMBO2                1155
#define IDC_PLACE_PARTY_BUTTON          1156
#define IDC_KILL_FOR_XP_BUTTON          1156
#define IDC_PLACE_ON_PARTY_BUTTON       1157
#define IDC_SWAP_WEAPON_BUTTON_1        1157
#define IDC_PLOT_PARTY_ROUTE_BUTTON     1158
#define IDC_SWAP_WEAPON_BUTTON_2        1158
#define IDC_HIDE_BUTTON                 1159
#define IDC_SUB_PARTY_BUTTON            1159
#define IDC_SHOW_BUTTON                 1160
#define IDC_RANDOM_ENCOUNTER_BUTTON     1160
#define IDC_PARTY_STATIC                1161
#define IDC_STAT_BLOCK_BUTTON           1161
#define IDC_CHAR_STATIC                 1162
#define IDC_STAT_BLOCK_BUTTON2          1162
#define IDC_PARENT_MAP_COMBO            1163
#define IDC_PLOT_PARTY_EXTEND_ROUTE_BUTTON 1163
#define IDC_PICK_LOCK_BUTTON            1163
#define IDC_PARTIES_CHECK               1164
#define IDC_RECOVER_AMMO_BUTTON         1164
#define IDC_ROUTES_CHECK                1165
#define IDC_CHILD_MAPS_CHECK            1166
#define IDC_SHOW_STATIC                 1167
#define IDC_CACHE_COMBO                 1168
#define IDC_HINT_STATIC                 1169
#define IDC_SCALE_MAP_BUTTON            1170
#define IDC_CACHE_STATIC                1170
#define IDC_SCALE_SLIDER                1171
#define IDC_AUTO_SCALE_MAP_BUTTON       1171
#define IDC_SCALE_STATIC                1172
#define IDC_RANDOM_DUNGEON_BUTTON       1172
#define IDC_TICKS_STATIC                1173
#define IDC_RELOAD_TILES_BUTTON         1173
#define IDC_PLACE_ON_CACHE_BUTTON       1174
#define IDC_CALENDAR_COMBO              1175
#define IDC_DELETE_CACHE_BUTTON         1175
#define IDC_YEAR_EDIT                   1176
#define IDC_PLACE_ON_CHARACTER_BUTTON   1176
#define IDC_INC_YEAR_BUTTON             1177
#define IDC_CACHES_CHECK                1177
#define IDC_DEC_YEAR_BUTTON             1178
#define IDC_PARTY_LEGEND                1178
#define IDC_LAYER_CHECK_1               1178
#define IDC_HOUR_EDIT                   1179
#define IDC_TRAVEL_BUTTON               1179
#define IDC_INC_HOUR_BUTTON             1180
#define IDC_UP_PARTY_BUTTON             1180
#define IDC_TRAVEL_MOUNTED_BUTTON       1180
#define IDC_DEC_HOUR_BUTTON             1181
#define IDC_DOWN_PARTY_BUTTON           1181
#define IDC_SPELL_LIST                  1181
#define IDC_REST_BUTTON                 1181
#define IDC_TURN_EDIT                   1182
#define IDC_UP_PARTY_BUTTON2            1182
#define IDC_LAYER_CHECK_2               1182
#define IDC_INC_TURN_BUTTON             1183
#define IDC_SOUND_BUTTON_1              1183
#define IDC_DOWN_PARTY_BUTTON2          1183
#define IDC_LAYER_CHECK_3               1183
#define IDC_DEC_TURN_BUTTON             1184
#define IDC_SOUND_BUTTON_2              1184
#define IDC_LAYER_CHECK_4               1184
#define IDC_ROUND_EDIT                  1185
#define IDC_SOUND_BUTTON_3              1185
#define IDC_SUBPARTY_COMBO              1185
#define IDC_INC_ROUND_BUTTON            1186
#define IDC_SOUND_BUTTON_4              1186
#define IDC_PARTY_STATIC2               1186
#define IDC_DEC_ROUND_BUTTON            1187
#define IDC_SOUND_BUTTON_5              1187
#define IDC_SUBPARTIES_CHECK            1187
#define IDC_SEGMENT_EDIT                1188
#define IDC_SOUND_BUTTON_6              1188
#define IDC_SCALE_SLIDER2               1188
#define IDC_INC_SEGMENT_BUTTON          1189
#define IDC_SOUND_BUTTON_7              1189
#define IDC_CHAR_ICONS_CHECK            1189
#define IDC_DEC_SEGMENT_BUTTON          1190
#define IDC_SOUND_BUTTON_8              1190
#define IDC_SCALE_STATIC2               1190
#define IDC_DAY_EDIT                    1191
#define IDC_SOUND_BUTTON_9              1191
#define IDC_TICKS_STATIC2               1191
#define IDC_INC_DAY_BUTTON              1192
#define IDC_SOUND_BUTTON_10             1192
#define IDC_ISOMETRIC_CHECK             1192
#define IDC_DEC_DAY_BUTTON              1193
#define IDC_SOUND_BUTTON_11             1193
#define IDC_LABELS_CHECK                1193
#define IDC_INC_EDIT_TIME_BUTTON        1194
#define IDC_SOUND_BUTTON_12             1194
#define IDC_INC_YEAR_BUTTON2            1194
#define IDC_START_CLOCK_BUTTON          1194
#define IDC_FOG_OF_WAR_CHECK            1194
#define IDC_SOUND_BUTTON_13             1195
#define IDC_VIEW_CALENDAR_BUTTON        1195
#define IDC_SCALE_SLIDER3               1195
#define IDC_SOUND_BUTTON_14             1196
#define IDC_VIEW_LOG_BUTTON             1196
#define IDC_SCALE_STATIC3               1196
#define IDC_MONTH_EDIT                  1197
#define IDC_SOUND_BUTTON_15             1197
#define IDC_GRANT_PARTY_XP_BUTTON       1197
#define IDC_TICKS_STATIC3               1197
#define IDC_INC_MONTH_BUTTON            1198
#define IDC_SOUND_BUTTON_16             1198
#define IDC_RAIN_CHECK                  1198
#define IDC_DEC_MONTH_BUTTON            1199
#define IDC_SOUND_BUTTON_17             1199
#define IDC_SNOW_CHECK                  1199
#define IDC_SOUND_BUTTON_18             1200
#define IDC_SEL_PARTY_CHECK             1200
#define IDC_SOUND_BUTTON_19             1201
#define IDC_SOUND_BUTTON_20             1202
#define IDC_SOUND_BUTTON_21             1203
#define IDC_SOUND_BUTTON_22             1204
#define IDC_SOUND_BUTTON_23             1205
#define IDC_SOUND_BUTTON_24             1206
#define IDC_SOUND_BUTTON_25             1207
#define IDC_SOUND_BUTTON_26             1208
#define IDC_SOUND_BUTTON_27             1209
#define IDC_SOUND_BUTTON_28             1210
#define IDC_SOUND_BUTTON_29             1211
#define IDC_SOUND_BUTTON_30             1212
#define IDC_SOUND_BUTTON_31             1213
#define IDC_SOUND_BUTTON_32             1214
#define IDC_SOUND_BUTTON_33             1215
#define IDC_SOUND_BUTTON_34             1216
#define IDC_SOUND_BUTTON_35             1217
#define IDC_SOUND_BUTTON_36             1218
#define IDC_SOUND_BUTTON_37             1219
#define IDC_SOUND_BUTTON_38             1220
#define IDC_SOUND_BUTTON_39             1221
#define IDC_SOUND_BUTTON_40             1222
#define IDC_SOUND_BUTTON_41             1223
#define IDC_SOUND_BUTTON_42             1224
#define IDC_SOUND_BUTTON_43             1225
#define IDC_SOUND_BUTTON_44             1226
#define IDC_SOUND_BUTTON_45             1227
#define IDC_SOUND_BUTTON_46             1228
#define IDC_SOUND_BUTTON_47             1229
#define IDC_SOUND_BUTTON_48             1230
#define IDC_SOUND_BUTTON_49             1231
#define IDC_SOUND_BUTTON_50             1232
#define IDC_SOUND_BUTTON_51             1233
#define IDC_SOUND_BUTTON_52             1234
#define IDC_SOUND_BUTTON_53             1235
#define IDC_SOUND_BUTTON_54             1236
#define IDC_SOUND_BUTTON_55             1237
#define IDC_SOUND_BUTTON_56             1238
#define IDC_SOUND_BUTTON_57             1239
#define IDC_SOUND_BUTTON_58             1240
#define IDC_SOUND_BUTTON_59             1241
#define IDC_SOUND_BUTTON_60             1242
#define IDC_SOUND_BUTTON_61             1243
#define IDC_SOUND_BUTTON_62             1244
#define IDC_SOUND_BUTTON_63             1245
#define IDC_SOUND_BUTTON_64             1246
#define IDC_SOUND_BUTTON_65             1247
#define IDC_SOUND_BUTTON_66             1248
#define IDC_SOUND_BUTTON_67             1249
#define IDC_SOUND_BUTTON_68             1250
#define IDC_SOUND_BUTTON_69             1251
#define IDC_SOUND_BUTTON_70             1252
#define IDC_SOUND_BUTTON_71             1253
#define IDC_SOUND_BUTTON_72             1254
#define IDC_SOUND_BUTTON_73             1255
#define IDC_SOUND_BUTTON_74             1256
#define IDC_SOUND_BUTTON_75             1257
#define IDC_SOUND_BUTTON_76             1258
#define IDC_SOUND_BUTTON_77             1259
#define IDC_SOUND_BUTTON_78             1260
#define IDC_SOUND_BUTTON_79             1261
#define IDC_SOUND_BUTTON_80             1262
#define IDC_PLAY_RADIO                  1263
#define IDC_EDIT_RADIO                  1327
#define IDC_SOUNDBOARD_TAB              1328
#define IDC_DESC_EDIT                   1329
#define IDC_CHOOSE_FILE_BUTTON          1330
#define IDC_BOARDNAME_EDIT              1331
#define IDC_CUT_SOUND_BUTTON            1331
#define IDC_BORDER_STATIC               1332
#define IDC_COPY_SOUND_BUTTON           1332
#define IDC_ENC_FACTOR_EDIT             1333
#define IDC_PASTE_SOUND_BUTTON          1333
#define IDC_GP_STATIC                   1334
#define IDC_CLEAR_SOUND_BUTTON          1334
#define IDC_RENAME_ITEM_EDIT            1335
#define IDC_INFLATION_FACTOR_EDIT       1335
#define IDC_INFLATION_STATIC            1336
#define IDC_MAP_WEAPON_SFX_BUTTON       1336
#define IDC_CACHE_NAME_EDIT             1336
#define IDC_MAP_SPELL_SFX_BUTTON        1337
#define IDC_CACHE_DETAILS_EDIT          1337
#define IDC_MONITOR_DPMI_EDIT           1337
#define IDC_TYPE_LABEL                  1338
#define IDC_ADD_BOARD_BUTTON            1338
#define IDC_DPMI_STATIC                 1338
#define IDC_EVENT_LIST                  1339
#define IDC_DELETE_BOARD_BUTTON         1339
#define IDC_SFX_LIST                    1340
#define IDC_EXPORT_BOARDS_BUTTON        1340
#define IDC_SWING_HIT_CHECK             1341
#define IDC_IMPORT_BOARDS_BUTTON        1341
#define IDC_SWING_MISS_CHECK            1342
#define IDC_RESET_DX_SOUNDS_BUTTON      1342
#define IDC_RANGED_HIT_CHECK            1343
#define IDC_RANGED_MISS_CHECK           1344
#define IDC_INFO_TEXT                   1345
#define IDC_SFX_MAP_1                   1346
#define IDC_MONSTER_CHECK               1346
#define IDC_SFX_MAP_2                   1347
#define IDC_NPC_CHECK                   1347
#define IDC_SFX_MAP_3                   1348
#define IDC_RACE_STATIC                 1348
#define IDC_SFX_MAP_4                   1349
#define IDC_CHAR_TYPE_COMBO             1349
#define IDC_CURRENT_CLASS_CHECK_1       1349
#define IDC_SHOW_ALL_CHECK              1350
#define IDC_HD_COMMENT                  1350
#define IDC_CURRENT_CLASS_CHECK_2       1350
#define IDC_CLERIC_SPELL_CHECK          1351
#define IDC_PLACE_CHARACTER_BUTTON      1351
#define IDC_CURRENT_CLASS_CHECK_3       1351
#define IDC_AC_COMMENT                  1351
#define IDC_MAGICUSER_SPELL_CHECK       1352
#define IDC_PARTY_CHARACTER_BUTTON      1352
#define IDC_ATT_COMMENT                 1352
#define IDC_DRUID_SPELL_CHECK           1353
#define IDC_PLACE_CACHE_BUTTON          1353
#define IDC_DMG_COMMENT                 1353
#define IDC_ILLUSIONIST_SPELL_CHECK     1354
#define IDC_TAB1                        1354
#define IDC_ADD_CACHE_BUTTON            1354
#define IDC_AC_COMMENT2                 1354
#define IDC_MOVE_COMMENT                1354
#define IDC_HEAL_PARTY_BUTTON           1355
#define IDC_DMG_COMMENT2                1355
#define IDC_SET_CHARACTER_ICON_BUTTON   1355
#define IDC_HEAL_PARTY_BUTTON2          1356
#define IDC_VERSION_STATIC              1356
#define IDC_LOG_EVENT_BUTTON            1356
#define IDC_PARTY_CHARACTERS_BUTTON     1356
#define IDC_PARTY_INITIATIVE_BUTTON     1357
#define IDC_CHARSHEET_SLIDER            1360
#define IDC_D20_BUTTON                  1361
#define IDC_NUM_DICE_EDIT               1362
#define IDC_RESULT_STATIC               1363
#define IDC_D12_BUTTON                  1364
#define IDC_XP_COMMENT                  1364
#define IDC_D10_BUTTON                  1365
#define IDC_WP_STATIC                   1365
#define IDC_DEBUG_CHAR_ID               1365
#define IDC_D6_BUTTON                   1366
#define IDC_INVENTORY_STATIC            1366
#define IDC_D100_BUTTON                 1367
#define IDC_INVENTORY_LABEL             1367
#define IDC_D4_BUTTON2                  1368
#define IDC_CACHE_NAME_STATIC           1368
#define IDC_D8_BUTTON                   1369
#define IDC_PLAYER_NAME_EDIT            1369
#define IDC_CACHE_DETAILS__STATIC       1369
#define IDC_DX_BUTTON                   1370
#define IDC_CHAR_CREATE_DATE_EDIT       1370
#define IDC_DETAILS_LOCATOR_BUTTON      1370
#define IDC_PLAYER_DEITY_EDIT           1371
#define IDC_WP_STATIC2                  1371
#define IDC_CHAR_ORIGIN_EDIT            1372
#define IDC_CHAR_HEIGHT_EDIT            1373
#define IDC_CHAR_WEIGHT_EDIT            1374
#define IDC_CHAR_DOB_MONTH_EDIT         1375
#define IDC_CHAR_DOB_DAY_EDIT           1376
#define IDC_CHAR_DOB_YEAR_EDIT          1377
#define IDC_PLAYER_RELIGION_EDIT        1378
#define IDC_CHAR_AGE_EDIT               1379
#define IDC_CHAR_AGE_ADJUST_EDIT        1380
#define IDC_CHAR_HAIR_COLOR_EDIT        1381
#define IDC_CHAR_EYE_COLOR_EDIT         1382
#define IDC_WILL_STATIC                 1383
#define IDC_PLAYER_RELIGION_EDIT2       1384
#define IDC_PLAYER_WILL_EDIT            1384
#define IDC_PREV_BUTTON                 1384
#define IDC_NEXT_BUTTON                 1385
#define IDC_PROMPT_TEXT                 1386
#define IDC_MARKER_BUTTON               1387
#define IDC_EVENT_TYPE_COMBO            1389
#define IDC_COMMENT_EDIT                1390
#define IDC_EVENT_TARGET_COMBO          1391
#define IDC_EVENT_TARGET_STATIC         1392
#define IDC_XP_EDIT                     1393
#define IDC_EVENT_VALUE_LABEL           1394
#define IDC_ADD_XP_BUTTON               1396
#define IDC_EDIT1                       1397
#define IDC_INPUT_EDIT                  1397
#define IDC_MULTI_EDIT                  1397
#define IDC_ENCOUNTER_EDIT              1397
#define IDC_DIE_ROLL_EDIT               1397
#define IDC_NOTES_EDIT                  1397
#define IDC_TT_MUL_EDIT                 1397
#define IDC_ITEM_NAME_EDIT              1397
#define IDC_DESCRIPTION_EDIT            1397
#define IDC_PROMPT_STATIC               1398
#define IDC_NUM_LIMIT_EDIT              1398
#define IDC_ITEM_COST_EDIT              1398
#define IDC_XP_VALUE_COMMENT            1399
#define IDC_ITEM_ENCUMBRANCE_EDIT       1399
#define IDC_ROLL_INIT_BUTTON            1400
#define IDC_NEXT_ROUND_BUTTON           1401
#define IDC_UP_LIST_BUTTON              1402
#define IDC_DOWN_LIST_BUTTON            1403
#define IDC_ROLL_PCS_CHECK              1404
#define IDC_HOURS_CHECK                 1405
#define IDC_ROLL_TARGETS_BUTTON         1405
#define IDC_WEATHER_CHECK               1406
#define IDC_COMELINESS_STATIC           1406
#define IDC_HIT_BUTTON                  1406
#define IDC_TYPE_RADIO1                 1407
#define IDC_MISS_BUTTON                 1407
#define IDC_TYPE_RADIO2                 1408
#define IDC_SPELL_BUTTON                1408
#define IDC_TYPE_RADIO3                 1409
#define IDC_WEAPON_SWAP_BUTTON          1409
#define IDC_TYPE_RADIO4                 1410
#define IDC_SKIP_BUTTON                 1410
#define IDC_TYPE_RADIO5                 1411
#define IDC_MOVE_BUTTON                 1411
#define IDC_TYPE_RADIO6                 1412
#define IDC_TYPE_RADIO7                 1413
#define IDC_TYPE_RADIO8                 1414
#define IDC_TYPE_RADIO9                 1415
#define IDC_TYPE_RADIO10                1416
#define IDC_AMOUNT_EDIT                 1417
#define IDC_SCROLL_SPELL_LIST           1418
#define IDC_CAST_BUTTON                 1419
#define IDC_COPY_SPELL_BUTTON           1420
#define IDC_RADIO1                      1420
#define IDC_ADD_SPELL_BUTTON            1421
#define IDC_RADIO2                      1421
#define IDC_DELETE_SPELL_BUTTON         1422
#define IDC_RADIO3                      1422
#define IDC_RADIO4                      1423
#define IDC_RADIO5                      1424
#define IDC_RADIO6                      1425
#define IDC_RADIO7                      1426
#define IDC_RADIO8                      1427
#define IDC_RADIO9                      1428
#define IDC_CLERIC_CHECK                1430
#define IDC_DRUID_CHECK                 1431
#define IDC_MAGICUSER_CHECK             1431
#define IDC_MAGIC_USER_CHECK            1432
#define IDC_ILLUSIONIST_CHECK           1433
#define IDC_MULTI_STATIC                1434
#define IDC_SCROLL_DETAILS_STATIC       1435
#define IDC_CHARGES_EDIT                1436
#define IDC_CHARGES_STATIC              1437
#define IDC_CONTAINER_DETAILS_STATIC    1438
#define IDC_PUT_IN_BUTTON               1439
#define IDC_TAKE_OUT_BUTTON             1440
#define IDC_CHECK1                      1440
#define IDC_CONTAINER_CONTENTS_CHECK    1440
#define IDC_TILES_CHECK                 1440
#define IDC_SEMI_EMPATH_CHECK           1440
#define IDC_CONTAINER_CHECK             1440
#define IDC_KEEN_EARED_CHECK            1440
#define IDC_MISSILE_CHECK               1440
#define IDC_DELETE_FILE_CHECK           1440
#define IDC_FILETYPES_CHECK             1440
#define IDC_SFX_CYCLE_CHECK             1440
#define IDC_PREREQ_ATTRIB_CHECK_0       1440
#define IDC_X1_CHECK                    1440
#define IDC_MALE_CHECK                  1440
#define IDC_SHOW_INSTALLED_CHECK        1440
#define IDC_PP_BUTTON                   1441
#define IDC_GRID_CHECK                  1441
#define IDC_EMPATH_CHECK                1441
#define IDC_RATIONS_CHECK               1441
#define IDC_KEEN_EARED_CHECK2           1441
#define IDC_AMMO_CHECK                  1441
#define IDC_PREREQ_ATTRIB_CHECK_1       1441
#define IDC_X2_CHECK                    1441
#define IDC_FEMALE_CHECK                1441
#define IDC_SFX_COLOR_KEYED_CHECK       1441
#define IDC_GP_BUTTON                   1442
#define IDC_PARTY_NAME_STATIC           1442
#define IDC_SPEECH_CHECK                1442
#define IDC_SWORD_CHECK                 1442
#define IDC_PREREQ_ATTRIB_CHECK_2       1442
#define IDC_X3_CHECK                    1442
#define IDC_SFX_TRANSLUCENT_CHECK       1442
#define IDC_EP_BUTTON                   1443
#define IDC_ENCOUNTER_LIST              1443
#define IDC_TELEPATH_CHECK              1443
#define IDC_EXCEPT_STR_CHECK            1443
#define IDC_PREREQ_ATTRIB_CHECK_3       1443
#define IDC_SP_BUTTON                   1444
#define IDC_ROLL_PARTY_STATIC           1444
#define IDC_PREREQ_ATTRIB_CHECK_4       1444
#define IDC_CP_BUTTON                   1445
#define IDC_LEVEL_COMBO                 1445
#define IDC_PREREQ_ATTRIB_CHECK_5       1445
#define IDC_ALL_COINS_BUTTON            1446
#define IDC_TABLE_COMBO                 1446
#define IDC_TYPE_COMBO                  1446
#define IDC_LANGUAGE_LIST               1447
#define IDC_COMPONENT_COMBO_1_1         1447
#define IDC_COMPONENT_COMBO_1_2         1448
#define IDC_LANGUAGES_FRAME             1449
#define IDC_COMPONENT_COMBO_1_3         1449
#define IDC_COMPONENT_COMBO_2_1         1450
#define IDC_LANGUAGES_LIST_BOX          1451
#define IDC_COMPONENT_COMBO_2_2         1451
#define IDC_SCROLLBAR1                  1452
#define IDC_FILE_SCROLLBAR              1452
#define IDC_COMPONENT_COMBO_2_3         1452
#define IDC_MONSTER_LEVEL_STATIC        1453
#define IDC_COMPONENT_COMBO_3_1         1453
#define IDC_ROOM_OCC_STATIC             1454
#define IDC_COMPONENT_COMBO_3_2         1454
#define IDC_TILE_SCROLLBAR              1455
#define IDC_COMPONENT_COMBO_3_3         1455
#define IDC_LEVEL_LABEL_STATIC          1456
#define IDC_NOTES_BUTTON                1457
#define IDC_DONE                        1458
#define IDC_DONE2                       1459
#define IDC_CHARS_REM_STATIC            1459
#define IDC_ITEM_IDENTIFIED_CHECK       1460
#define IDC_IN_LAIR_CHECK               1461
#define IDC_TREASURE_TYPE_LIST          1462
#define IDC_MAGIC_SWORD_STATIC          1463
#define IDC_ALIGNMENT_COMBO             1465
#define IDC_SELECT_LANGUAGES_BUTTON     1467
#define IDC_PRIMARY_ABILITY_BUTTON_1    1468
#define IDC_STRING_LIST                 1468
#define IDC_PRIMARY_ABILITY_BUTTON_2    1469
#define IDC_SPECIALIZED_CHECK           1469
#define IDC_PRIMARY_ABILITY_BUTTON_3    1470
#define IDC_DOUBLE_SPECIALIZED_CHECK    1470
#define IDC_ITEM_LIST                   1470
#define IDC_EXCEPTIONAL_POWER_BUTTON    1471
#define IDC_NEW_ITEM_BUTTON             1471
#define IDC_SPECIAL_PURPOSE_BUTTON      1472
#define IDC_SAVE_ITEM_BUTTON            1472
#define IDC_SPECIAL_PURPOSE_POWER_BUTTON 1473
#define IDC_COIN_COMBO                  1473
#define IDC_DELETE_ITEM_BUTTON          1474
#define IDC_CLERIC_RADIO                1474
#define IDC_ARMOR_CLASS_COMBO           1474
#define IDC_DRUID_RADIO                 1475
#define IDC_MAGIC_USER_RADIO            1476
#define IDC_ILLUSIONIST_RADIO           1477
#define IDC_SPELL_NAME_EDIT             1478
#define IDC_REVERSIBLE_CHECK            1479
#define IDC_VERBAL_CHECK                1480
#define IDC_MONSTER_LIST                1480
#define IDC_SOMATIC_CHECK               1481
#define IDC_NEW_MONSTER_BUTTON          1481
#define IDC_MATERIAL_CHECK              1482
#define IDC_DELETE_MONSTER_BUTTON       1482
#define IDC_SPELL_RANGE_EDIT            1483
#define IDC_SAVE_MONSTER_BUTTON         1483
#define IDC_SPELL_CASTING_TIME_EDIT     1484
#define IDC_MONSTER_TYPE_EDIT           1484
#define IDC_SPELL_DURATION_EDIT         1485
#define IDC_SPELL_SAVING_THROW_EDIT     1486
#define IDC_SPELL_AREA_OF_EFFECT_EDIT   1487
#define IDC_MONSTER_ATTACK_EDIT         1487
#define IDC_SPELL_NAME_EDIT2            1488
#define IDC_SPELL_DESCRIPTION_EDIT      1488
#define IDC_MONSTER_DEFENSE_EDIT        1488
#define IDC_SAVE_SPELL_BUTTON           1489
#define IDC_MAGIC_RESIST_COMBO          1489
#define IDC_DEBUG_SPELL_BUTTON          1490
#define IDC_MONSTER_HD_EDIT             1490
#define IDC_SECONDARY_SKILL_COMBO       1490
#define IDC_NEW_SPELL_BUTTON            1491
#define IDC_DESC_COMBO                  1491
#define IDC_NEW_ARMOR_BUTTON            1491
#define IDC_LIGHT_SOURCE_COMBO          1491
#define IDC_ALL_RADIO                   1492
#define IDC_MONSTER_AC_EDIT             1492
#define IDC_DELETE_ARMOR_BUTTON         1492
#define IDC_INT_COMBO                   1493
#define IDC_SAVE_ARMOR_BUTTON           1493
#define IDC_COMPONENT_AMOUNT_EDIT_1_1   1493
#define IDC_MONSTER_SIZE_EDIT           1494
#define IDC_ARMOR_NAME_EDIT             1494
#define IDC_COMPONENT_AMOUNT_EDIT_1_2   1494
#define IDC_MONSTER_ATTACKS_EDIT        1495
#define IDC_ARMOR_ENCUMBRANCE_EDIT      1495
#define IDC_COMPONENT_AMOUNT_EDIT_1_3   1495
#define IDC_MONSTER_DAMAGE_EDIT         1496
#define IDC_ARMOR_COST_EDIT             1496
#define IDC_COMPONENT_AMOUNT_EDIT_2_1   1496
#define IDC_MONSTER_AC_EDIT2            1497
#define IDC_ARMOR_XP_EDIT               1497
#define IDC_COMPONENT_AMOUNT_EDIT_2_2   1497
#define IDC_MONSTER_TREASURE_TYPE_EDIT  1498
#define IDC_THIEF_CHECK                 1498
#define IDC_COMPONENT_AMOUNT_EDIT_2_3   1498
#define IDC_METAL_CHECK                 1499
#define IDC_COMPONENT_AMOUNT_EDIT_3_1   1499
#define IDC_ARMOR_LIST                  1500
#define IDC_COMPONENT_AMOUNT_EDIT_3_2   1500
#define IDC_MOVE_COMBO                  1501
#define IDC_COMPONENT_AMOUNT_EDIT_3_3   1501
#define IDC_WEAPON_NAME_EDIT            1508
#define IDC_WEAPON_ENCUMBRANCE_EDIT     1509
#define IDC_WEAPON_COST_EDIT            1510
#define IDC_WEAPON_XP_EDIT              1511
#define IDC_NEW_WEAPON_BUTTON           1512
#define IDC_DELETE_WEAPON_BUTTON        1513
#define IDC_SAVE_WEAPON_BUTTON          1514
#define IDC_AMMO_TYPE_STATIC            1515
#define IDC_WEAPON_LIST                 1516
#define IDC_WEAPON_VS_AC_EDIT0          1517
#define IDC_WEAPON_VS_AC_EDIT1          1518
#define IDC_WEAPON_VS_AC_EDIT2          1519
#define IDC_WEAPON_VS_AC_EDIT3          1520
#define IDC_WEAPON_VS_AC_EDIT4          1521
#define IDC_WEAPON_VS_AC_EDIT5          1522
#define IDC_WEAPON_VS_AC_EDIT6          1523
#define IDC_WEAPON_VS_AC_EDIT7          1524
#define IDC_WEAPON_VS_AC_EDIT8          1525
#define IDC_WEAPON_VS_AC_EDIT9          1526
#define IDC_WEAPON_VS_AC_EDIT10         1527
#define IDC_DAMAGE_SMALL_LOW            1528
#define IDC_DAMAGE_SMALL_HIGH           1529
#define IDC_DAMAGE_LARGE_LOW            1530
#define IDC_DAMAGE_LARGE_HIGH           1531
#define IDC_SPACE_REQD                  1532
#define IDC_WEAPON_SPEED                1533
#define IDC_DEBUG_STRING                1534
#define IDC_TEXT_BOX                    1536
#define IDC_FILE_BUTTON_1               1537
#define IDC_FILE_BUTTON_2               1538
#define IDC_FILE_BUTTON_3               1539
#define IDC_FILE_BUTTON_4               1540
#define IDC_FILE_BUTTON_5               1541
#define IDC_FILE_BUTTON_6               1542
#define IDC_FILE_BUTTON_7               1543
#define IDC_FILE_BUTTON_8               1544
#define IDC_FILE_BUTTON_9               1545
#define IDC_FILE_BUTTON_10              1546
#define IDC_FILE_BUTTON_11              1547
#define IDC_FILE_BUTTON_12              1548
#define IDC_FILE_BUTTON_13              1549
#define IDC_FILE_BUTTON_14              1550
#define IDC_FILE_BUTTON_15              1551
#define IDC_FILE_BUTTON_16              1552
#define IDC_GROUP_STATIC                1553
#define IDC_DEBUG_STATIC                1556
#define IDC_NEW_FOLDER_BUTTON           1557
#define IDC_COPY_BUTTON                 1558
#define IDC_PASTE_BUTTON                1559
#define IDC_CELL_LABEL                  1559
#define IDC_NEW_FOLDER_BUTTON2          1560
#define IDC_DELETE_FOLDER_BUTTON        1560
#define IDC_EDIT_LAYER_1                1560
#define IDC_EDIT_LAYER_2                1561
#define IDC_DEBUG_TEXT                  1561
#define IDC_EDIT_LAYER_3                1562
#define IDC_TILE_HEIGHT_SLIDER          1562
#define IDC_ATTACKS_TEXT                1562
#define IDC_EDIT_LAYER_4                1563
#define IDC_TILE_HEIGHT_STATIC          1563
#define IDC_DELETE_LAYER_1              1564
#define IDC_RESIZE_CELL_BUTTON          1564
#define IDC_DELETE_LAYER_2              1565
#define IDC_RESIZE_MAP_BUTTON           1565
#define IDC_DELETE_LAYER_3              1566
#define IDC_PROGRESS1                   1566
#define IDC_DELETE_LAYER_4              1567
#define IDC_EFFECT_NAME_EDIT            1567
#define IDC_EFFECT_GFX_EDIT             1568
#define IDC_SOUND_FX_COMBO              1569
#define IDC_PAGE_STATIC                 1571
#define IDC_PAGE_EDIT                   1572
#define IDC_SEARCH_EDIT                 1573
#define IDC_DMG_BUTTON                  1575
#define IDC_CLASS_NAME_COMBO            1576
#define IDC_HD_TYPE_EDIT                1577
#define IDC_BASE_LEVEL_XP_EDIT_1        1578
#define IDC_MAX_LEVEL_XP_EDIT_1         1579
#define IDC_HD_LEVEL_EDIT_1             1580
#define IDC_BASE_LEVEL_XP_EDIT_2        1581
#define IDC_MAX_LEVEL_XP_EDIT_2         1582
#define IDC_HD_LEVEL_EDIT_2             1583
#define IDC_BASE_LEVEL_XP_EDIT_3        1584
#define IDC_MAX_LEVEL_XP_EDIT_3         1585
#define IDC_HD_LEVEL_EDIT_3             1586
#define IDC_BASE_LEVEL_XP_EDIT_4        1587
#define IDC_MAX_LEVEL_XP_EDIT_4         1588
#define IDC_HD_LEVEL_EDIT_4             1589
#define IDC_BASE_LEVEL_XP_EDIT_5        1590
#define IDC_MAX_LEVEL_XP_EDIT_5         1591
#define IDC_HD_LEVEL_EDIT_5             1592
#define IDC_BASE_LEVEL_XP_EDIT_6        1593
#define IDC_MAX_LEVEL_XP_EDIT_6         1594
#define IDC_HD_LEVEL_EDIT_6             1595
#define IDC_BASE_LEVEL_XP_EDIT_7        1596
#define IDC_MAX_LEVEL_XP_EDIT_7         1597
#define IDC_HD_LEVEL_EDIT_7             1598
#define IDC_BASE_LEVEL_XP_EDIT_8        1599
#define IDC_MAX_LEVEL_XP_EDIT_8         1600
#define IDC_HD_LEVEL_EDIT_8             1601
#define IDC_BASE_LEVEL_XP_EDIT_9        1602
#define IDC_MAX_LEVEL_XP_EDIT_9         1603
#define IDC_HD_LEVEL_EDIT_9             1604
#define IDC_BASE_LEVEL_XP_EDIT_10       1605
#define IDC_MAX_LEVEL_XP_EDIT_10        1606
#define IDC_HD_LEVEL_EDIT_10            1607
#define IDC_BASE_LEVEL_XP_EDIT_11       1608
#define IDC_MAX_LEVEL_XP_EDIT_11        1609
#define IDC_HD_LEVEL_EDIT_11            1610
#define IDC_BASE_LEVEL_XP_EDIT_12       1611
#define IDC_MAX_LEVEL_XP_EDIT_12        1612
#define IDC_HD_LEVEL_EDIT_12            1613
#define IDC_MAX_LEVEL_XP_EDIT           1614
#define IDC_HD_MAX_LEVEL_EDIT           1615
#define IDC_HD_MIN_HP_EDIT              1616
#define IDC_HD_MAX_HP_EDIT              1617
#define IDC_SAVING_THROW_CLASS_COMBO    1618
#define IDC_MAGIC_USE_CLASS_COMBO       1619
#define IDC_MAGIC_LEVEL_EDIT            1620
#define IDC_INIT_WEAPON_PROF_EDIT       1621
#define IDC_COMBAT_CHART_COMBO          1622
#define IDC_THIEF_SKILLS_CHECK          1623
#define IDC_THIEF_LEVEL_EDIT            1624
#define IDC_ASSASSIN_SKILLS_CHECK       1625
#define IDC_ASSASSIN_LEVEL_EDIT         1626
#define IDC_TURN_UNDEAD_CHECK           1627
#define IDC_TURN_UNDEAD_LEVEL_EDIT      1628
#define IDC_ADD_WEAPON_PROF_EDIT        1629
#define IDC_ADD_WEAPON_PROF_LEVELS_EDIT 1630
#define IDC_NON_WEAPON_PROF_PENALTY_EDIT 1631
#define IDC_DEX_COMMENT_STATIC          1632
#define IDC_FILTER_EDIT                 1633
#define IDC_SWORD_ICON                  1634
#define IDC_GO_BUTTON                   1635
#define IDC_ADD_ON_PROGRESS             1636
#define IDC_FILE_NAME_STATIC            1637
#define IDC_ADD_ONS_LIST                1638
#define IDC_FILE_SIZE_STATIC            1639
#define IDC_ENCRYPT_BUTTON              1639
#define IDC_FILE_PERC_STATIC            1640
#define IDC_EXPLAIN_TEXT                1640
#define IDC_HUMAN_BUTTON                1643
#define IDC_ELVEN_BUTTON                1644
#define IDC_ALPHA_EDIT                  1644
#define IDC_DWARVEN_BUTTON              1645
#define IDC_MATERIAL_COMPONENTS         1645
#define IDC_HALFLING_BUTTON             1646
#define IDC_COMPONENTS_LIST             1646
#define IDC_TRANSCRIBE_SPELL            1646
#define IDC_GNOME_BUTTON                1647
#define IDC_COMPONENTS_LINE             1647
#define IDC_BUGBEAR_BUTTON              1648
#define IDC_BUY_COMPONENTS_BUTTON       1648
#define IDC_DRAGON_BUTTON               1649
#define IDC_GIVE_COMPONENTS_BUTTON      1649
#define IDC_AND_STATIC_1                1649
#define IDC_GOBLIN_BUTTON               1650
#define IDC_GIVE_ALL_COMPONENTS_BUTTON  1650
#define IDC_AND_STATIC_2                1650
#define IDC_HOBGOBLIN_BUTTON            1651
#define IDC_BUY_ALL_COMPONENTS_BUTTON   1651
#define IDC_AND_STATIC_3                1651
#define IDC_KOBOLD_BUTTON               1652
#define IDC_AND_STATIC_4                1652
#define IDC_OGRE_BUTTON                 1653
#define IDC_AND_STATIC_5                1653
#define IDC_ORC_BUTTON                  1654
#define IDC_AND_STATIC_6                1654
#define IDC_OR_STATIC_1                 1655
#define IDC_OR_STATIC_2                 1656
#define IDC_OR_STATIC_3                 1657
#define IDC_OR_STATIC_4                 1658
#define IDC_OR_STATIC_5                 1659
#define IDC_OR_STATIC_6                 1660
#define IDC_COMPONENTS_LABEL            1661
#define IDC_X_STATIC_1                  1662
#define IDC_SPELL_DESC                  1662
#define IDC_X_STATIC_2                  1663
#define IDC_SAVING_THROW_BOX            1663
#define IDC_X_STATIC_3                  1664
#define IDC_SAVING_THROWS_MOD_BUTTON    1664
#define IDC_X_STATIC_4                  1665
#define IDC_LANGUAGES_MOD_BUTTON        1665
#define IDC_X_STATIC_5                  1666
#define IDC_THIEF_SKILLS_MOD_BUTTON     1666
#define IDC_X_STATIC_6                  1667
#define IDC_ASSASSIN_SKILLS_MOD_BUTTON  1667
#define IDC_X_STATIC_7                  1668
#define IDC_CLERIC_TURN_MOD_BUTTON      1668
#define IDC_X_STATIC_8                  1669
#define IDC_XP1_LABEL                   1669
#define IDC_X_STATIC_9                  1670
#define IDC_XP2_LABEL                   1670
#define IDC_XP3_LABEL                   1671
#define ID_FAIL_CAST                    1672
#define IDC_LEVEL_TITLE_1               1673
#define IDC_LEVEL_TITLE_2               1674
#define IDC_DAY_NAME                    1674
#define IDC_LEVEL_TITLE_3               1675
#define IDC_MONTH_NAME                  1675
#define IDC_COMMENT                     1676
#define ID_OPEN_CHARACTER               32771
#define ID_CLOSE_CHARACTER              32772
#define ID_NEW_CHARACTER                32773
#define ID_OPEN_MAP                     32774
#define ID_CLOSE_MAP                    32775
#define ID_NEW_MAP                      32776
#define ID_OPEN_PARTY                   32777
#define ID_CLOSE_PARTY                  32778
#define ID_NEW_PARTY                    32779
#define ID_OPEN_SOUNDBOARD              32780
#define ID_CLOSE_SOUNDBOARD             32781
#define ID_HELP_ABOUTDUNGEONMAESTRO     32782
#define ID_DICEROLLER_OPENDICERROLLER   32783
#define ID_HELP_DUNGEONMAESTROUSER      32784
#define ID_PARTIES_SUBPARTIES           32785
#define ID_SUBPARTIES_ADDSUBPARTY       32786
#define ID_SUBPARTIES_REMOVESUBPARTY    32787
#define ID_HELP_CHECKFORUPDATES         32788
#define ID_CUSTOMIZATIONS_CUSTOMITEMS   32789
#define ID_CUSTOMIZATIONS_CUSTOMSPELLEDITOR 32790
#define ID_CUSTOMIZATIONS_CUSTOMMONSTER 32791
#define ID_CUSTOMIZATIONS_CUSTOMARMOREDITOR 32792
#define ID_CUSTOMIZATIONS_CUSTOMWEAPONEDITOR 32793
#define ID_SUBPARTIES_SORTSUBPARTIES    32794
#define ID_SUBPARTIES_SORTSUBPARTIESNUMERICALLY 32795
#define ID_DMLIBRARY_DUNGEONMASTER      32796
#define ID_DMLIBRARY_PLAYER             32797
#define ID_DMLIBRARY_MONSTERMANUAL      32798
#define ID_DMLIBRARY_MONSTERMANUAL2     32799
#define ID_DMLIBRARY_FIENDFOLIO         32800
#define ID_DMLIBRARY_UNEARTHEDARCANA    32801
#define ID_DMLIBRARY_FROMFILE           32802
#define ID_CUSTOMIZATIONS_CUSTOMCLASSEDITOR 32803
#define ID_HELP_CHECKFORADD             32804
#define ID_RANDOMS_RANDOMNAMEGENERATOR  32805
#define ID_RANDOMS_RANDOMNAMEGENERATOR32806 32806
#define ID_PARTIES_AUTOSAVEPARTIES      32807
#define ID_MAPS_SPELLFXONMAPS           32808
#define ID_SPELLFXONMAPS_ENABLED        32809
#define ID_SPELLFXONMAPS_ENABLEDFORMAGICMISSILE 32810
#define ID_DMLIBRARY_CHARTSTABLES       32811
#define ID_CHARTSANDTABLES_SAVINGTHROWMATRIXFORMAGICALANDNON 32812
#define ID_CHARTSANDTABLES_POTIONMISCIBILITYTABLE 32813
#define ID_CHARTSANDTABLES_TREASURETYPES 32814

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        301
#define _APS_NEXT_COMMAND_VALUE         32815
#define _APS_NEXT_CONTROL_VALUE         1677
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
